import type React from 'react';

export const styles: Record<string, React.CSSProperties> = {
  page: {
    width: "100%",
    minHeight: "100vh",
    backgroundColor: "#f8fafc",
    fontFamily: "'Inter', system-ui, -apple-system, sans-serif",
    color: "#1e293b",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "0 40px",
    height: "72px",
    backgroundColor: "#ffffff",
    borderBottom: "1px solid #e2e8f0",
    position: "sticky",
    top: 0,
    zIndex: 100,
    width: "100%",
    boxSizing: "border-box",
  },
  logo: {
    fontSize: "1.25rem",
    fontWeight: 800,
    color: "#0f172a",
  },
  headerRight: {
    display: "flex",
    alignItems: "center",
    gap: 12,
  },
  studentBadge: {
    fontSize: "12px",
    fontWeight: 600,
    backgroundColor: "#eff6ff",
    color: "#2563eb",
    padding: "4px 12px",
    borderRadius: "999px",
  },
  main: {
    width: "100%",
    maxWidth: "600px",
    margin: "0 auto",
    padding: "40px 20px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    boxSizing: "border-box",
  },
  centered: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    minHeight: "100vh",
    width: "100vw",
    backgroundColor: "#f9fafb",
    position: "fixed",
    top: 0,
    left: 0,
    zIndex: 999,
  },
  card: {
    backgroundColor: "#ffffff",
    borderRadius: 20,
    padding: 40,
    width: "100%",
    maxWidth: 420,
    boxShadow: "0 10px 25px -5px rgba(0, 0, 0, 0.1)",
  },
  title: {
    margin: "0 0 8px",
    fontSize: 24,
    fontWeight: 700,
    color: "#111827",
  },
  subtitle: {
    margin: "0 0 24px",
    fontSize: 14,
    color: "#6b7280",
    lineHeight: 1.5,
  },
  input: {
    width: "100%",
    padding: "12px 14px",
    fontSize: 15,
    border: "1.5px solid #d1d5db",
    borderRadius: 10,
    outline: "none",
    boxSizing: "border-box",
    marginBottom: 8,
    fontFamily: "inherit",
  },
  errorText: {
    color: "#ef4444",
    fontSize: 13,
    margin: "0 0 8px",
  },
  primaryButton: {
    width: "100%",
    marginTop: 12,
    padding: "12px 0",
    backgroundColor: "#2563eb",
    color: "#ffffff",
    fontSize: 15,
    fontWeight: 600,
    border: "none",
    borderRadius: 10,
    cursor: "pointer",
    fontFamily: "inherit",
  },
  questionCard: {
    backgroundColor: "#ffffff",
    borderRadius: 16,
    padding: 24,
    marginBottom: 20,
    boxShadow: "0 2px 12px rgba(0,0,0,0.06)",
    width: "100%",
    boxSizing: "border-box",
  },
  question: {
    margin: 0,
    fontSize: 20,
    fontWeight: 700,
    color: "#111827",
    lineHeight: 1.4,
  },
  optionsGrid: {
    display: "flex",
    flexDirection: "column",
    gap: 12,
    width: "100%",
  },
  optionButton: {
    padding: "14px 20px",
    fontSize: 15,
    fontWeight: 500,
    textAlign: "left",
    backgroundColor: "#ffffff",
    color: "#111827",
    border: "2px solid #e5e7eb",
    borderRadius: 12,
    cursor: "pointer",
    transition: "all 0.15s ease",
    fontFamily: "inherit",
  },
  optionSelected: {
    backgroundColor: "#eff6ff",
    borderColor: "#2563eb",
    color: "#1d4ed8",
    fontWeight: 700,
  },
  optionDisabled: {
    opacity: 0.5,
    cursor: "not-allowed",
  },
  resultsCard: {
    backgroundColor: "#ffffff",
    borderRadius: "24px",
    padding: "40px",
    width: "100%",
    boxShadow: "0 10px 25px -5px rgba(0, 0, 0, 0.05)",
    border: "1px solid #f1f5f9",
    boxSizing: "border-box",
  },
  resultsTitle: {
    margin: "0 0 8px",
    fontSize: "22px",
    fontWeight: 800,
    color: "#0f172a",
    textAlign: "center",
  },
  resultsQuestion: {
    fontSize: "15px",
    color: "#64748b",
    textAlign: "center",
    marginBottom: "32px",
    lineHeight: "1.5",
  },
  resultsList: {
    display: "flex",
    flexDirection: "column",
    gap: "24px",
    width: "100%",
  },
  resultRow: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    width: "100%",
  },
  resultLabelRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
    fontSize: "15px",
    fontWeight: 600,
  },
  resultLabel: {
    color: "#334155",
  },
  resultPct: {
    color: "#0f172a",
    fontWeight: 800,
  },
  resultTrack: {
    width: "100%",
    height: "10px",
    backgroundColor: "#f1f5f9",
    borderRadius: "10px",
    overflow: "hidden",
  },
  resultFill: {
    height: "100%",
    borderRadius: "10px",
    transition: "width 0.8s cubic-bezier(0.4, 0, 0.2, 1)",
  },
  resultCount: {
    fontSize: "12px",
    color: "#94a3b8",
    textAlign: "right",
  },
  waitingNext: {
    marginTop: "32px",
    fontSize: "14px",
    color: "#94a3b8",
    textAlign: "center",
    fontStyle: "italic",
  },
  waitingCard: {
    backgroundColor: "#ffffff",
    borderRadius: 16,
    padding: "48px 32px",
    textAlign: "center",
    width: "100%",
    boxShadow: "0 2px 12px rgba(0,0,0,0.06)",
  },
  waitingIcon: {
    fontSize: 48,
    marginBottom: 16,
    lineHeight: 1,
  },
  waitingTitle: {
    margin: "0 0 8px",
    fontSize: 20,
    fontWeight: 700,
    color: "#111827",
  },
  waitingSubtitle: {
    margin: "0 0 24px",
    fontSize: 14,
    color: "#6b7280",
    lineHeight: 1.5,
  },
};