import type React from 'react';

export const styles: Record<string, React.CSSProperties> = {
  centered: {
    display: "flex",
    justifyContent: "center", 
    alignItems: "center",   
    minHeight: "100vh",       
    width: "100vw",           
    backgroundColor: "#f0f4ff",
    position: "fixed",        
    top: 0,
    left: 0,
  },
  card: {
    backgroundColor: "#ffffff",
    borderRadius: 20,
    padding: "40px 36px",
    width: "100%",
    maxWidth: 440,
    boxShadow: "0 8px 40px rgba(0,0,0,0.10)",
  },
  logoRow: {
    display: "flex",
    alignItems: "center",
    gap: 14,
    marginBottom: 24,
  },
  logo: { fontSize: 40, lineHeight: 1 },
  appName: {
    margin: 0,
    fontSize: 24,
    fontWeight: 800,
    color: "#1e3a5f",
    lineHeight: 1.2,
  },
  tagline: { margin: "4px 0 0", fontSize: 13, color: "#6b7280" },
  divider: { height: 1, backgroundColor: "#e5e7eb", marginBottom: 24 },
  prompt: {
    margin: "0 0 14px",
    fontSize: 14,
    fontWeight: 600,
    color: "#374151",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  roleGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12, marginBottom: 24 },
  roleCard: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 6,
    padding: "20px 12px",
    backgroundColor: "#f8fafc",
    border: "2px solid #e5e7eb",
    borderRadius: 14,
    cursor: "pointer",
    transition: "border-color 0.15s, background-color 0.15s",
    fontFamily: "inherit",
  },
  roleIcon: { fontSize: 28, lineHeight: 1 },
  roleLabel: { fontSize: 15, fontWeight: 700, color: "#111827" },
  roleHint: { fontSize: 12, color: "#9ca3af", textAlign: "center" },
  badgeRow: { display: "flex", justifyContent: "center" },
};